{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-webview-multiplatform/2.0.4-js1/compose-webview-multiplatform-2.0.4-js1.module",
    "group": "io.github.kevinnzou",
    "module": "compose-webview-multiplatform",
    "version": "2.0.4-js1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview-wasm-js.klib",
          "url": "compose-webview-multiplatform-wasm-js-2.0.4-js1.klib",
          "size": 230147,
          "sha512": "13b9f472759da1c8487ebafe5b722ac3a32f2e276e457aef1f9b88f4a4a00d34060d53d73eac231ceabfe31fdb664c8f7f8c17b407112e762b05e423cd1c5928",
          "sha256": "2d0d1597270697d742a4e570486eeffaa0fbb7405719a989de9a3912a184e3ba",
          "sha1": "1f5c623a0c65c51f53361defcad70d64518ed662",
          "md5": "10836384fbf1228a15ddb8669534a6c7"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "webview-wasm-js.klib",
          "url": "compose-webview-multiplatform-wasm-js-2.0.4-js1.klib",
          "size": 230147,
          "sha512": "13b9f472759da1c8487ebafe5b722ac3a32f2e276e457aef1f9b88f4a4a00d34060d53d73eac231ceabfe31fdb664c8f7f8c17b407112e762b05e423cd1c5928",
          "sha256": "2d0d1597270697d742a4e570486eeffaa0fbb7405719a989de9a3912a184e3ba",
          "sha1": "1f5c623a0c65c51f53361defcad70d64518ed662",
          "md5": "10836384fbf1228a15ddb8669534a6c7"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "webview-wasm-js-sources.jar",
          "url": "compose-webview-multiplatform-wasm-js-2.0.4-js1-sources.jar",
          "size": 49545,
          "sha512": "73fb5c01fb52e3dc3d79d5babd46163255205a1717e71be081aa6db6302dcbafd1fe9de7866420efcf5abef8a1c98cb490e17cf1ff5747ce324f70b910139722",
          "sha256": "d829b87f9cd896aeafd7a36431768cf7b71d9a46417fe0c9d260e51aeba65197",
          "sha1": "43e6eb36354b3c42b65ef855624cbca0050a60cf",
          "md5": "1f6074d46e840fbcabec2802f278f984"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "webview.kotlin_resources.zip",
          "url": "compose-webview-multiplatform-wasm-js-2.0.4-js1-kotlin_resources.kotlin_resources.zip",
          "size": 362,
          "sha512": "735ddaf521e370e81b244dd781006ac20e6386840aedd1c03d81e8dc1e6b97c9ca8caa6b47d0175e8b81a0a0d26d7c669a8b17ce4b4084ed34d270811594c161",
          "sha256": "b3bca01da9c1c303094dc4f904282b760b96dc005e9fed049402e8646daa903a",
          "sha1": "0fb997012a363c71aa791ef4b953da1f88e1c324",
          "md5": "bd5475ef71db9a18c07223c1d048fa35"
        }
      ]
    }
  ]
}
