{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-webview-multiplatform/2.0.4-js1/compose-webview-multiplatform-2.0.4-js1.module",
    "group": "io.github.kevinnzou",
    "module": "compose-webview-multiplatform",
    "version": "2.0.4-js1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "webview-iosX64Main.klib",
          "url": "compose-webview-multiplatform-iosx64-2.0.4-js1.klib",
          "size": 204530,
          "sha512": "1785c2971359e22c0d79ee884fd9260b876da1f1fbded769e898b75272bcb31366a11b996a9b9379e37720e11964cdceedbce16ae8de10f3c958442cb4374358",
          "sha256": "87832e23b5d15e6d89ed34e8ed429aff67afec918b8fedd715629f06b95abbfc",
          "sha1": "7484047540657cfd1218d24b85d8ce4861e70921",
          "md5": "857d5b4c5e5a634eff9e3b62a648d284"
        },
        {
          "name": "webview-iosX64Cinterop-observerMain.klib",
          "url": "compose-webview-multiplatform-iosx64-2.0.4-js1-cinterop-observer.klib",
          "size": 5918,
          "sha512": "1e6e287eea555592c035d7cfd9707876c5afd8c03f470fcc639e09cd1523d2d645e3c7b3fff5b903d81c7e5da79213ab5dbd6b7ebd77eef56918bceeb16a1679",
          "sha256": "61a34f5257c8e3a851252e104b83cbc1f6f73b18b0af3d588dc934b3df7d23d9",
          "sha1": "802343efd19784bde42568e69cfb59049d1dedf6",
          "md5": "50f49b3c886704bbf62ad95b570412ae"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "webview-iosx64-sources.jar",
          "url": "compose-webview-multiplatform-iosx64-2.0.4-js1-sources.jar",
          "size": 43774,
          "sha512": "4fff99334b1b368103e796a72786bd4fc15b6b21d33baa6d6308a4ea8ce93ed70f2f6f40a310c84e7c8a8ff63dc221c4106a2465cebebc9585656d8cb7052328",
          "sha256": "cf10617bf4602c79d705f7f8894677ce3a4814e0141ff495449d4ecf4df02250",
          "sha1": "f9523b3c1136e02350bf54f2a705072253601247",
          "md5": "cf556d0f3487a8bac50ec6c6e4b5e956"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "webview.kotlin_resources.zip",
          "url": "compose-webview-multiplatform-iosx64-2.0.4-js1-kotlin_resources.kotlin_resources.zip",
          "size": 362,
          "sha512": "735ddaf521e370e81b244dd781006ac20e6386840aedd1c03d81e8dc1e6b97c9ca8caa6b47d0175e8b81a0a0d26d7c669a8b17ce4b4084ed34d270811594c161",
          "sha256": "b3bca01da9c1c303094dc4f904282b760b96dc005e9fed049402e8646daa903a",
          "sha1": "0fb997012a363c71aa791ef4b953da1f88e1c324",
          "md5": "bd5475ef71db9a18c07223c1d048fa35"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "webview-iosx64-metadata.jar",
          "url": "compose-webview-multiplatform-iosx64-2.0.4-js1-metadata.jar",
          "size": 18831,
          "sha512": "5cc79ecbd5938c855d4f160bb0e09199045f5f38efb131d7fdf9799891258cfc73e7358582ee45a04b605c9144832c5fba7c9f632a1bfd464fa413a0fb8e18c0",
          "sha256": "2ca52caf312458be900407697bf4c06c059f203c0b49c656a630af02b8c8ec8f",
          "sha1": "ebd0d20cfe7c5d8353bd51d679f790fa69bc3b06",
          "md5": "6ec75044cefcc4de87ca2a30673a56d0"
        }
      ]
    }
  ]
}
