{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-webview-multiplatform/2.0.4-js2/compose-webview-multiplatform-2.0.4-js2.module",
    "group": "io.github.kevinnzou",
    "module": "compose-webview-multiplatform",
    "version": "2.0.4-js2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "webview-iosSimulatorArm64Main.klib",
          "url": "compose-webview-multiplatform-iossimulatorarm64-2.0.4-js2.klib",
          "size": 204761,
          "sha512": "ad0231ee9368c2ddb3d66224d9d55a29685facddae5d958b31af8996bc6d93214def244563f3932e9e82aeaf27f7dbffa6962659798dd25f8886dc537011ef21",
          "sha256": "1da79c4425465658058ef7df6b5cebc7e155ead0c359ebcf1f4d3459806f32d5",
          "sha1": "c8d41ce4bfa1a46ff1f42cf4b85eb15357a67886",
          "md5": "df747f8a23a03d436bced1b3df0a1436"
        },
        {
          "name": "webview-iosSimulatorArm64Cinterop-observerMain.klib",
          "url": "compose-webview-multiplatform-iossimulatorarm64-2.0.4-js2-cinterop-observer.klib",
          "size": 6114,
          "sha512": "ef67b7accf2c1483739ec0f1ff8d889fac593f6e27d38643e7dfe554ea91efb56a4d526f67c5b4114871705064d75a03b48ac5776c40c9a090c9ba96d466155a",
          "sha256": "67695d43ece0a8340bb40f23a49c619df066576e691d7e1438aad29d321a375d",
          "sha1": "69557cb947c8b10125728845d5fc0762d8def8be",
          "md5": "0dd92aaa92d4b1f5796f92c032892d46"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "webview-iossimulatorarm64-sources.jar",
          "url": "compose-webview-multiplatform-iossimulatorarm64-2.0.4-js2-sources.jar",
          "size": 43947,
          "sha512": "d15f66df54ca57ff1d129527df31b7e4d3c07705cb213f8693b706620f0159cd733cf7af52bf08bff47fc271f7279e48a90b758d0a53282f5f35a4847d85572b",
          "sha256": "5e4ae2a520fdd42c44b5e10fb6d4a458dd0117eb4c415294c0b2155cbe309d9d",
          "sha1": "cedc7f0bac2865d5633f6fc3a70c5cb610c9021e",
          "md5": "f9b9c84d8d621c92503dc2b43553beca"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "webview.kotlin_resources.zip",
          "url": "compose-webview-multiplatform-iossimulatorarm64-2.0.4-js2-kotlin_resources.kotlin_resources.zip",
          "size": 362,
          "sha512": "735ddaf521e370e81b244dd781006ac20e6386840aedd1c03d81e8dc1e6b97c9ca8caa6b47d0175e8b81a0a0d26d7c669a8b17ce4b4084ed34d270811594c161",
          "sha256": "b3bca01da9c1c303094dc4f904282b760b96dc005e9fed049402e8646daa903a",
          "sha1": "0fb997012a363c71aa791ef4b953da1f88e1c324",
          "md5": "bd5475ef71db9a18c07223c1d048fa35"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "webview-iossimulatorarm64-metadata.jar",
          "url": "compose-webview-multiplatform-iossimulatorarm64-2.0.4-js2-metadata.jar",
          "size": 18825,
          "sha512": "03db0f9567c63b6f30713bd39565be038cc0cb4f750d0d7dbc9b0d1dc11f1461a5f965408fd3b83ce4828534801a0df958bb8067ec13ef72c5a3e070f34cb797",
          "sha256": "7d747d6a61a0fd4f7583206d2fa0bedcd0f978e923d8fc517d517fa309cbcf9a",
          "sha1": "2513a1fa76de955e4208f017263c6c2c773e1adb",
          "md5": "5ae352bb1fb3dcb555f147e94006ed55"
        }
      ]
    }
  ]
}
